config/routes.rb
Selector::Application.routes.draw do
  root :to => "addresses#index"
  resources :addresses
  
  get '/states', :to => "states#index"
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :country
  belongs_to :state 
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
    collect_form_data
  end

  def create
    @address = Address.create(address_params)
    flash[:notice] = "Address has been created"
    redirect_to addresses_path
  end

  def edit
    find_address
    collect_form_data
  end

  def update
    find_address
    @address.update_attributes(address_params)
    flash[:notice] = "Address has been updated"
    redirect_to addresses_path
  end

  def destroy
    find_address
    @address.destroy
    flash[:notice] = "Address has been destroyed"
    redirect_to addresses_path
  end

  private

  def collect_form_data
    @countries = Country.order("name ASC")
    if @address.country
      @states = @address.country.states
    else
      @states = @countries.first.states
    end
  end

  def find_address
    @address ||= Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  respond_to :json

  def index
    country = Country.find(params[:country_id])
    respond_with(country.states) if stale?(country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/addresses/_form.html.erb
<%= form_for @address do |f| %>
  <p id='country_field'>
    <%= f.label :country_id %><br>
    <%= f.select :country_id, @countries.map { |c| [c.name, c.id] } %>
  </p>

  <p id='state_field'> 
    <%= f.label :state_id %><br>
    <%= f.select :state_id, @states.map  { |s| [s.name, s.id] } %>
  </p>

  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/addresses/edit.html.erb
<h2>Editing Address</h2>

<%= render "form" %>

app/views/addresses/index.html.erb
<h2>Addresses</h2>

<%= link_to "New Address", new_address_path, :class => "btn btn-primary" %>

<table class='table'>
  <thead>
    <th>Country</th>
    <th>State</th>
    <th>Edit</th>
    <th>Destroy</th>
  </thead>
  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.country.name %></td>
        <td><%= address.state.name %></td>
        <td><%= link_to "Edit", edit_address_path(address) %></td>
        <td><%= link_to "Destroy", address_path(address), :method => :delete, :data => { :confirm => "Are you sure you want to destroy  this address? "} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/addresses/new.html.erb
<h2>New Address</h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Selector</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>